name: RaidTheMine-Core
version: '${project.version}'
main: com.jordanhaddrick.rtm.Main
api-version: 1.18
authors: [SomeKidsBrother, Someone]
description: Core plugin for RaidTheMine
website: www.RaidTheMine.com
commands:
  wild:
    description: Teleport to a random location
    usage: /<command>
    permission: rtm.wild
  kit:
    description: Access the kits you have access to
    usage: /<command>
  gms:
    description: Changes your gamemode to survival
    usage: /<command>
    permission: rtm.gms
  gmc:
    description: Changes your gamemode to creative
    usage: /<command>
    permission: rtm.gmc
  gmsp:
    description: Changes your gamemode to spectator
    usage: /<command>
    permission: rtm.gmsp
  feed:
    description: Fulfill someone's needs
    usage: /<command>
    permission: rtm.feed
  heal:
    description: Heal someone back to full health
    usage: /<command>
    permission: rtm.heal
  fly:
    description: Toggle your flight
    usage: /<command>
    permission: rtm.fly
  god:
    description: Become invunerable
    usage: /<command>
    permission: rtm.god