########################################################
## GLOBAL CONFIG
########################################################

# Set the prefix
prefix-message: "<bold><gold>SERVER</gold> <dark_gray>>></dark_gray></bold>"

non-player-message: "<red>You need to be a player to execute this command.</red>"

invalid-player-message: "<gradient:#FF0000:#FF3DC5>Invalid player!</gradient>"

########################################################
## RANDOM TP /WILD
########################################################

# True if you want to limit how far it teleports players
world-border: false

# How many blocks away they CAN spawn(not will)
# If no world border, limit is automatically 25,000 blocks
border: 200

# Wild cool-down time
cool-down-time: 10

# Message displayed when player still in cool off period
cool-down-message: "<white>You can use</white> <aqua>/wild</aqua> <white>again in</white> <red>{seconds-left}</red> <white>seconds.</white>"

# Message displayed when a player is in the nether or end world
incorrect-world-message: "<white>You cannot use</white> <aqua>/wild</aqua> <white>in this world.</white>"

# Message displayed when a player uses the wild command wrong
incorrect-wild-usage-message: "<red>Incorrect usage!</red> <aqua>/wild</aqua>"

# Message displayed when a player is teleported
random-location: "<white>You have been teleported to a random location.</white>"

queued-teleport-message: "<gradient:#00FFEC:#FF00FB>Teleporting...</gradient>"

########################################################
## RANK KITS /KIT
########################################################

# Message displayed when a player is given a kit
kit-message: "<gradient:#00FFEC:#FF00FB>You've been given the kit.</gradient>"

available-kit-message: "<red>Please specify the kit you wish to use!</red>"

incorrect-kit-usage-message: "<red>Incorrect kit!</red> <aqua>Please try again with a correct kit name.</aqua>"

########################################################
## GAMEMODE COMMANDS
########################################################

# Gamemode messages
gamemode-message: "<gradient:#00FFEC:#FF00FB>Your gamemode has been changed to <type>!</gradient>"

incorrect-gamemode-usage-message: "<gradient:#00FFEC:#FF00FB>Your gamemode is already <type>!</gradient>"

incorrect-gamemode-other-usage-message: "<gradient:#00FFEC:#FF00FB><player>'s gamemode is already <type>!</gradient>"

gamemode-other: "<gradient:#00FFEC:#FF00FB>You've set <player>'s gamemode to <type>!</gradient>"

########################################################
## FEED COMMAND
########################################################
feed-message: "<gradient:#00FFEC:#FF00FB>You've been fed!</gradient>"

feed-other-message: "<gradient:#00FFEC:#FF00FB>You fed <player>!</gradient>"

########################################################
## HEAL COMMAND
########################################################

heal-message: "<gradient:#00FFEC:#FF00FB>You've been healed!</gradient>"

heal-other-message: "<gradient:#00FFEC:#FF00FB>You healed <player>!</gradient>"

########################################################
## FLY COMMAND
########################################################

fly-enabled-message: "<gradient:#00FFEC:#FF00FB>Your flight has been enabled!</gradient>"
fly-disabled-message: "<gradient:#00FFEC:#FF00FB>Your flight has been disabled!</gradient>"

fly-enabled-other-message: "<gradient:#00FFEC:#FF00FB>You enabled flight for <player>!</gradient>"
fly-disabled-other-message: "<gradient:#00FFEC:#FF00FB>You disabled flight for <player>!</gradient>"