name: RaidTheMine-Core
version: '1.0'
main: com.jordanhaddrick.rtm.Main
api-version: 1.18
authors: [SomeKidsBrother, Someone]
depend: [Vault]
description: Core plugin for RaidTheMine
website: www.RaidTheMine.com
commands:
  wild:
    description: Teleport to a random location
    usage: /<command>
  kit:
    description: Access the kits you have access to
    usage: /<command>
  gms:
    description: Changes your gamemode to survival
    usage: /<command>
  gmc:
    description: Changes your gamemode to creative
    usage: /<command>
  gmsp:
    description: Changes your gamemode to spectator
    usage: /<command>
  feed:
    description: Fulfill someone's needs
    usage: /<command>
  heal:
    description: Heal someone back to full health
    usage: /<command>
  fly:
    description: Toggle your flight
    usage: /<command>
  god:
    description: Become invunerable
    usage: /<command>
  msg:
    description: Privately message someone
    usage: /<command>
  tp:
    description: Teleport to someone
    usage: /<command>
  tphere:
    description: Teleport to someone to you
    usage: /<command>
  speed:
    description: Change your walking speed
    usage: /<command>